-- Seeds the full 385-achievement catalog from the design handoff
-- (quiz_achievements_dansk_korrektur.xlsx). `criteria` is populated only
-- for the ~65 achievements evaluable today (Games Played, Questions, Wins,
-- Answer Streaks, Perfection, Category Mastery) -- the rest seed with
-- criteria = NULL and show as locked/"coming soon" until their evaluator
-- ships in a follow-up (most need features that do not exist yet: avatars,
-- difficulty levels, referrals, sharing, a ladder-rank system, etc.).
INSERT INTO "Achievement" ("id", "nameEn", "nameDa", "descEn", "descDa", "group", "tier", "rarity", "criteria") VALUES
('ACH-001', 'First Steps', 'De første skridt', 'Play 1 game in any mode', 'Spil 1 spil i valgfri tilstand', 'Games Played', 'bronze', 'common', '{"type": "games_played", "min": 1, "mode": null}'::jsonb),
('ACH-002', 'Getting Warm', 'Godt i gang', 'Play 5 games in any mode', 'Spil 5 spil i valgfri tilstand', 'Games Played', 'bronze', 'common', '{"type": "games_played", "min": 5, "mode": null}'::jsonb),
('ACH-003', 'Regular', 'Stamgæst', 'Play 10 games in any mode', 'Spil 10 spil i valgfri tilstand', 'Games Played', 'silver', 'common', '{"type": "games_played", "min": 10, "mode": null}'::jsonb),
('ACH-004', 'Committed', 'Dedikeret', 'Play 25 games in any mode', 'Spil 25 spil i valgfri tilstand', 'Games Played', 'silver', 'uncommon', '{"type": "games_played", "min": 25, "mode": null}'::jsonb),
('ACH-005', 'Half Century', 'Halvtreds på bagen', 'Play 50 games in any mode', 'Spil 50 spil i valgfri tilstand', 'Games Played', 'gold', 'uncommon', '{"type": "games_played", "min": 50, "mode": null}'::jsonb),
('ACH-006', 'Centurion', 'Centurion', 'Play 100 games in any mode', 'Spil 100 spil i valgfri tilstand', 'Games Played', 'gold', 'rare', '{"type": "games_played", "min": 100, "mode": null}'::jsonb),
('ACH-007', 'Quiz Addict', 'Quizafhængig', 'Play 250 games in any mode', 'Spil 250 spil i valgfri tilstand', 'Games Played', 'platinum', 'rare', '{"type": "games_played", "min": 250, "mode": null}'::jsonb),
('ACH-008', 'Devoted', 'Hengiven', 'Play 500 games in any mode', 'Spil 500 spil i valgfri tilstand', 'Games Played', 'diamond', 'epic', '{"type": "games_played", "min": 500, "mode": null}'::jsonb),
('ACH-009', 'Millennium Mind', 'Tusindkunstner', 'Play 1000 games in any mode', 'Spil 1000 spil i valgfri tilstand', 'Games Played', 'legendary', 'legendary', '{"type": "games_played", "min": 1000, "mode": null}'::jsonb),
('ACH-010', 'Quiz Legend', 'Quizlegende', 'Play 2500 games in any mode', 'Spil 2500 spil i valgfri tilstand', 'Games Played', 'mythic', 'legendary', '{"type": "games_played", "min": 2500, "mode": null}'::jsonb),
('ACH-011', 'Solo Starter', 'Solostarter', 'Play 5 games in Regular Mode', 'Spil 5 spil i normal tilstand', 'Games Played', 'bronze', 'common', '{"type": "games_played", "min": 5, "mode": "regular"}'::jsonb),
('ACH-012', 'Lone Wolf', 'Ensom ulv', 'Play 10 games in Regular Mode', 'Spil 10 spil i normal tilstand', 'Games Played', 'silver', 'common', '{"type": "games_played", "min": 10, "mode": "regular"}'::jsonb),
('ACH-013', 'Solo Grinder', 'Soloslider', 'Play 50 games in Regular Mode', 'Spil 50 spil i normal tilstand', 'Games Played', 'gold', 'uncommon', '{"type": "games_played", "min": 50, "mode": "regular"}'::jsonb),
('ACH-014', 'Solo Centurion', 'Solocenturion', 'Play 100 games in Regular Mode', 'Spil 100 spil i normal tilstand', 'Games Played', 'platinum', 'rare', '{"type": "games_played", "min": 100, "mode": "regular"}'::jsonb),
('ACH-015', 'Solo Sage', 'Solovismand', 'Play 500 games in Regular Mode', 'Spil 500 spil i normal tilstand', 'Games Played', 'diamond', 'epic', '{"type": "games_played", "min": 500, "mode": "regular"}'::jsonb),
('ACH-016', 'Solo Immortal', 'Udødelig solist', 'Play 1000 games in Regular Mode', 'Spil 1000 spil i normal tilstand', 'Games Played', 'legendary', 'legendary', '{"type": "games_played", "min": 1000, "mode": "regular"}'::jsonb),
('ACH-017', 'Party of One', 'Første fest', 'Play 1 game in Party Mode', 'Spil 1 spil i Party Mode', 'Games Played', 'bronze', 'common', '{"type": "games_played", "min": 1, "mode": "party"}'::jsonb),
('ACH-018', 'Party Guest', 'Festgæst', 'Play 5 games in Party Mode', 'Spil 5 spil i Party Mode', 'Games Played', 'silver', 'common', '{"type": "games_played", "min": 5, "mode": "party"}'::jsonb),
('ACH-019', 'Party Regular', 'Fast festgæst', 'Play 10 games in Party Mode', 'Spil 10 spil i Party Mode', 'Games Played', 'gold', 'common', '{"type": "games_played", "min": 10, "mode": "party"}'::jsonb),
('ACH-020', 'Party Animal', 'Festabe', 'Play 50 games in Party Mode', 'Spil 50 spil i Party Mode', 'Games Played', 'platinum', 'uncommon', '{"type": "games_played", "min": 50, "mode": "party"}'::jsonb),
('ACH-021', 'Party Centurion', 'Festcenturion', 'Play 100 games in Party Mode', 'Spil 100 spil i Party Mode', 'Games Played', 'diamond', 'rare', '{"type": "games_played", "min": 100, "mode": "party"}'::jsonb),
('ACH-022', 'Party Machine', 'Festmaskine', 'Play 500 games in Party Mode', 'Spil 500 spil i Party Mode', 'Games Played', 'legendary', 'epic', '{"type": "games_played", "min": 500, "mode": "party"}'::jsonb),
('ACH-023', 'Party Legend', 'Festlegende', 'Play 1000 games in Party Mode', 'Spil 1000 spil i Party Mode', 'Games Played', 'mythic', 'legendary', '{"type": "games_played", "min": 1000, "mode": "party"}'::jsonb),
('ACH-024', 'Curious', 'Nysgerrig', 'Answer 100 questions (right or wrong)', 'Besvar 100 spørgsmål (rigtigt eller forkert)', 'Questions', 'bronze', 'common', '{"type": "questions_answered", "min": 100}'::jsonb),
('ACH-025', 'Inquisitive', 'Videbegærlig', 'Answer 500 questions (right or wrong)', 'Besvar 500 spørgsmål (rigtigt eller forkert)', 'Questions', 'silver', 'common', '{"type": "questions_answered", "min": 500}'::jsonb),
('ACH-026', 'Knowledge Seeker', 'Vidensjæger', 'Answer 1,000 questions (right or wrong)', 'Besvar 1.000 spørgsmål (rigtigt eller forkert)', 'Questions', 'gold', 'uncommon', '{"type": "questions_answered", "min": 1000}'::jsonb),
('ACH-027', 'Scholar', 'Lærd', 'Answer 5,000 questions (right or wrong)', 'Besvar 5.000 spørgsmål (rigtigt eller forkert)', 'Questions', 'platinum', 'rare', '{"type": "questions_answered", "min": 5000}'::jsonb),
('ACH-028', 'Professor', 'Professor', 'Answer 10,000 questions (right or wrong)', 'Besvar 10.000 spørgsmål (rigtigt eller forkert)', 'Questions', 'diamond', 'rare', '{"type": "questions_answered", "min": 10000}'::jsonb),
('ACH-029', 'Sage', 'Vismand', 'Answer 25,000 questions (right or wrong)', 'Besvar 25.000 spørgsmål (rigtigt eller forkert)', 'Questions', 'legendary', 'epic', '{"type": "questions_answered", "min": 25000}'::jsonb),
('ACH-030', 'Walking Encyclopedia', 'Vandrende leksikon', 'Answer 50,000 questions (right or wrong)', 'Besvar 50.000 spørgsmål (rigtigt eller forkert)', 'Questions', 'mythic', 'legendary', '{"type": "questions_answered", "min": 50000}'::jsonb),
('ACH-031', 'Sharp Mind', 'Skarp hjerne', 'Answer 50 questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål (samlet)', 'Questions', 'bronze', 'common', '{"type": "questions_correct", "min": 50}'::jsonb),
('ACH-032', 'Brainiac', 'Kloge-Åge', 'Answer 250 questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål (samlet)', 'Questions', 'silver', 'uncommon', '{"type": "questions_correct", "min": 250}'::jsonb),
('ACH-033', 'Mastermind', 'Mesterhjerne', 'Answer 1,000 questions correctly (lifetime)', 'Svar rigtigt på 1.000 spørgsmål (samlet)', 'Questions', 'gold', 'rare', '{"type": "questions_correct", "min": 1000}'::jsonb),
('ACH-034', 'Genius', 'Geni', 'Answer 5,000 questions correctly (lifetime)', 'Svar rigtigt på 5.000 spørgsmål (samlet)', 'Questions', 'platinum', 'rare', '{"type": "questions_correct", "min": 5000}'::jsonb),
('ACH-035', 'Oracle', 'Orakel', 'Answer 10,000 questions correctly (lifetime)', 'Svar rigtigt på 10.000 spørgsmål (samlet)', 'Questions', 'diamond', 'epic', '{"type": "questions_correct", "min": 10000}'::jsonb),
('ACH-036', 'Omniscient', 'Alvidende', 'Answer 25,000 questions correctly (lifetime)', 'Svar rigtigt på 25.000 spørgsmål (samlet)', 'Questions', 'legendary', 'legendary', '{"type": "questions_correct", "min": 25000}'::jsonb),
('ACH-037', 'First Blood', 'Første sejr', 'Win 1 game', 'Vind 1 spil', 'Wins', 'bronze', 'common', '{"type": "wins", "min": 1}'::jsonb),
('ACH-038', 'Winner Winner', 'Sejrherre', 'Win 10 games', 'Vind 10 spil', 'Wins', 'silver', 'common', '{"type": "wins", "min": 10}'::jsonb),
('ACH-039', 'Podium Regular', 'Fast på podiet', 'Win 25 games', 'Vind 25 spil', 'Wins', 'gold', 'uncommon', '{"type": "wins", "min": 25}'::jsonb),
('ACH-040', 'Dominator', 'Dominator', 'Win 50 games', 'Vind 50 spil', 'Wins', 'platinum', 'uncommon', '{"type": "wins", "min": 50}'::jsonb),
('ACH-041', 'Champion', 'Mester', 'Win 100 games', 'Vind 100 spil', 'Wins', 'diamond', 'rare', '{"type": "wins", "min": 100}'::jsonb),
('ACH-042', 'Conqueror', 'Erobrer', 'Win 250 games', 'Vind 250 spil', 'Wins', 'legendary', 'epic', '{"type": "wins", "min": 250}'::jsonb),
('ACH-043', 'Dynasty', 'Dynasti', 'Win 500 games', 'Vind 500 spil', 'Wins', 'mythic', 'legendary', '{"type": "wins", "min": 500}'::jsonb),
('ACH-044', 'Hot Hand', 'God stime', 'Win 3 games in a row', 'Vind 3 spil i træk', 'Wins', 'silver', 'uncommon', '{"type": "win_streak", "min": 3}'::jsonb),
('ACH-045', 'Undefeated', 'Ubesejret', 'Win 5 games in a row', 'Vind 5 spil i træk', 'Wins', 'gold', 'rare', '{"type": "win_streak", "min": 5}'::jsonb),
('ACH-046', 'Unbeatable', 'Uovervindelig', 'Win 10 games in a row', 'Vind 10 spil i træk', 'Wins', 'platinum', 'epic', '{"type": "win_streak", "min": 10}'::jsonb),
('ACH-047', 'Untouchable', 'Urørlig', 'Win 25 games in a row', 'Vind 25 spil i træk', 'Wins', 'diamond', 'legendary', '{"type": "win_streak", "min": 25}'::jsonb),
('ACH-048', 'Comeback Kid', 'Comeback-kongen', 'Win a game after being in last place at the halfway point', 'Vind et spil efter at have ligget sidst ved halvvejsmærket', 'Wins', 'gold', 'rare', NULL),
('ACH-049', 'Photo Finish', 'Fotofinish', 'Win a game by exactly 1 point', 'Vind et spil med præcis 1 point', 'Wins', 'gold', 'rare', '{"type": "win_margin_exact", "points": 1}'::jsonb),
('ACH-050', 'Landslide', 'Jordskredssejr', 'Win with at least double the runner-up''s score', 'Vind med mindst det dobbelte af toerens score', 'Wins', 'gold', 'rare', '{"type": "win_margin_ratio", "ratio": 2}'::jsonb),
('ACH-051', 'Buzzer Beater', 'I sidste sekund', 'Take the lead for the first time on the final question and win', 'Tag føringen for første gang på sidste spørgsmål – og vind', 'Wins', 'platinum', 'epic', NULL),
('ACH-052', 'Wire to Wire', 'Fra start til slut', 'Lead from the first question to the last and win', 'Før fra første til sidste spørgsmål og vind', 'Wins', 'gold', 'rare', NULL),
('ACH-053', 'Warming Up', 'Varmer op', 'Answer 3 questions correctly in a row within one game', 'Svar rigtigt på 3 spørgsmål i træk i ét spil', 'Answer Streaks', 'bronze', 'common', '{"type": "answer_streak_in_game", "min": 3}'::jsonb),
('ACH-054', 'On a Roll', 'På en stime', 'Answer 5 questions correctly in a row within one game', 'Svar rigtigt på 5 spørgsmål i træk i ét spil', 'Answer Streaks', 'silver', 'common', '{"type": "answer_streak_in_game", "min": 5}'::jsonb),
('ACH-055', 'Heating Up', 'Godt kørende', 'Answer 10 questions correctly in a row within one game', 'Svar rigtigt på 10 spørgsmål i træk i ét spil', 'Answer Streaks', 'gold', 'uncommon', '{"type": "answer_streak_in_game", "min": 10}'::jsonb),
('ACH-056', 'On Fire', 'Brandvarm', 'Answer 15 questions correctly in a row within one game', 'Svar rigtigt på 15 spørgsmål i træk i ét spil', 'Answer Streaks', 'gold', 'rare', '{"type": "answer_streak_in_game", "min": 15}'::jsonb),
('ACH-057', 'Unstoppable', 'Ustoppelig', 'Answer 20 questions correctly in a row within one game', 'Svar rigtigt på 20 spørgsmål i træk i ét spil', 'Answer Streaks', 'platinum', 'epic', '{"type": "answer_streak_in_game", "min": 20}'::jsonb),
('ACH-058', 'Inhuman', 'Umenneskelig', 'Answer 25 questions correctly in a row within one game', 'Svar rigtigt på 25 spørgsmål i træk i ét spil', 'Answer Streaks', 'diamond', 'legendary', '{"type": "answer_streak_in_game", "min": 25}'::jsonb),
('ACH-059', 'Streak Collector', 'Stimesamler', 'Reach a 5+ answer streak 100 times (lifetime)', 'Opnå en stime på mindst 5 rigtige svar 100 gange (samlet)', 'Answer Streaks', 'silver', 'uncommon', '{"type": "answer_streak_lifetime_count", "streakMin": 5, "timesMin": 100}'::jsonb),
('ACH-060', 'Streak Hoarder', 'Stimehamstrer', 'Reach a 5+ answer streak 500 times (lifetime)', 'Opnå en stime på mindst 5 rigtige svar 500 gange (samlet)', 'Answer Streaks', 'gold', 'rare', '{"type": "answer_streak_lifetime_count", "streakMin": 5, "timesMin": 500}'::jsonb),
('ACH-061', 'Streak Tycoon', 'Stimebaron', 'Reach a 5+ answer streak 1000 times (lifetime)', 'Opnå en stime på mindst 5 rigtige svar 1000 gange (samlet)', 'Answer Streaks', 'platinum', 'epic', '{"type": "answer_streak_lifetime_count", "streakMin": 5, "timesMin": 1000}'::jsonb),
('ACH-062', 'Perfect Game', 'Perfekt spil', 'Finish a game with 100% correct answers', 'Gennemfør et spil med 100 % rigtige svar', 'Perfection', 'gold', 'rare', '{"type": "perfect_games", "min": 1}'::jsonb),
('ACH-063', 'Double Perfect', 'Dobbelt perfekt', 'Finish 2 games with 100% correct answers (lifetime)', 'Gennemfør 2 spil med 100 % rigtige svar (samlet)', 'Perfection', 'platinum', 'epic', '{"type": "perfect_games", "min": 2}'::jsonb),
('ACH-064', 'Perfect Ten', 'Perfekt ti''er', 'Finish 10 games with 100% correct answers (lifetime)', 'Gennemfør 10 spil med 100 % rigtige svar (samlet)', 'Perfection', 'diamond', 'epic', '{"type": "perfect_games", "min": 10}'::jsonb),
('ACH-065', 'Perfect Fifty', 'Perfekt halvtreds', 'Finish 50 games with 100% correct answers (lifetime)', 'Gennemfør 50 spil med 100 % rigtige svar (samlet)', 'Perfection', 'legendary', 'legendary', '{"type": "perfect_games", "min": 50}'::jsonb),
('ACH-066', 'Back-to-Back Flawless', 'To perfekte i træk', 'Get two perfect games in a row', 'Få to perfekte spil i træk', 'Perfection', 'diamond', 'legendary', '{"type": "perfect_games_consecutive", "min": 2}'::jsonb),
('ACH-067', 'Flawless Week', 'Fejlfri uge', 'Get at least one perfect game every day for 7 days', 'Få mindst ét perfekt spil hver dag i 7 dage', 'Perfection', 'diamond', 'legendary', NULL),
('ACH-068', 'Perfect Party', 'Perfekt fest', 'Get 100% correct in a Party Mode game with 4+ players', 'Svar 100 % rigtigt i et Party Mode-spil med mindst 4 spillere', 'Perfection', 'platinum', 'epic', '{"type": "perfect_game_min_players", "minPlayers": 4}'::jsonb),
('ACH-069', 'Habit Forming', 'Vanedannende', 'Play at least one game 3 days in a row', 'Spil mindst ét spil 3 dage i træk', 'Daily Streaks', 'bronze', 'common', NULL),
('ACH-070', 'One Week Wonder', 'En hel uge', 'Play at least one game 7 days in a row', 'Spil mindst ét spil 7 dage i træk', 'Daily Streaks', 'silver', 'common', NULL),
('ACH-071', 'Fortnight Fighter', 'Fjorten dage i træk', 'Play at least one game 14 days in a row', 'Spil mindst ét spil 14 dage i træk', 'Daily Streaks', 'silver', 'uncommon', NULL),
('ACH-072', 'Monthly Devotion', 'En hel måned', 'Play at least one game 30 days in a row', 'Spil mindst ét spil 30 dage i træk', 'Daily Streaks', 'gold', 'uncommon', NULL),
('ACH-073', 'Two Month Titan', 'To måneder i træk', 'Play at least one game 60 days in a row', 'Spil mindst ét spil 60 dage i træk', 'Daily Streaks', 'gold', 'rare', NULL),
('ACH-074', 'Quarter Master', 'Kvartalsmester', 'Play at least one game 90 days in a row', 'Spil mindst ét spil 90 dage i træk', 'Daily Streaks', 'platinum', 'rare', NULL),
('ACH-075', 'Half-Year Hero', 'Halvårshelt', 'Play at least one game 180 days in a row', 'Spil mindst ét spil 180 dage i træk', 'Daily Streaks', 'diamond', 'epic', NULL),
('ACH-076', 'Year of the Quiz', 'Quizzens år', 'Play at least one game 365 days in a row', 'Spil mindst ét spil 365 dage i træk', 'Daily Streaks', 'legendary', 'legendary', NULL),
('ACH-077', 'Phoenix', 'Fugl Føniks', 'Rebuild a 7-day streak after losing one of 7+ days', 'Genopbyg en 7-dages stime efter at have mistet en stime på mindst 7 dage', 'Daily Streaks', 'gold', 'rare', NULL),
('ACH-078', 'Streak Saver', 'Stimeredder', 'Play with less than 1 hour left in the day to keep a streak alive', 'Spil med under 1 time tilbage af dagen for at holde din stime i live', 'Daily Streaks', 'silver', 'uncommon', NULL),
('ACH-079', 'Quick Draw', 'Hurtig på aftrækkeren', 'Answer a question correctly in under 2 seconds', 'Svar rigtigt på et spørgsmål på under 2 sekunder', 'Speed', 'bronze', 'common', NULL),
('ACH-080', 'Lightning Round', 'Lynrunde', 'Answer 5 questions correctly in under 3 seconds each in one game', 'Svar rigtigt på 5 spørgsmål på under 3 sekunder hver i ét spil', 'Speed', 'gold', 'rare', NULL),
('ACH-081', 'Speed Demon', 'Fartdjævel', 'Give 100 correct answers in under 3 seconds (lifetime)', 'Giv 100 rigtige svar på under 3 sekunder (samlet)', 'Speed', 'silver', 'uncommon', NULL),
('ACH-082', 'Speedster', 'Hurtigløber', 'Give 500 correct answers in under 3 seconds (lifetime)', 'Giv 500 rigtige svar på under 3 sekunder (samlet)', 'Speed', 'gold', 'rare', NULL),
('ACH-083', 'Sonic Mind', 'Lynhjerne', 'Give 1,000 correct answers in under 3 seconds (lifetime)', 'Giv 1.000 rigtige svar på under 3 sekunder (samlet)', 'Speed', 'platinum', 'epic', NULL),
('ACH-084', 'Faster Than Light', 'Hurtigere end lyset', 'Give 5,000 correct answers in under 3 seconds (lifetime)', 'Giv 5.000 rigtige svar på under 3 sekunder (samlet)', 'Speed', 'diamond', 'legendary', NULL),
('ACH-085', 'Down to the Wire', 'På målstregen', 'Answer correctly with less than 0.5 seconds remaining', 'Svar rigtigt med under et halvt sekund tilbage', 'Speed', 'gold', 'rare', NULL),
('ACH-086', 'Clutch Collector', 'Iskold afslutter', 'Answer correctly in the last second 25 times (lifetime)', 'Svar rigtigt i sidste sekund 25 gange (samlet)', 'Speed', 'gold', 'rare', NULL),
('ACH-087', 'Tortoise Wins', 'Skildpadden vinder', 'Win a game while having the slowest average answer time', 'Vind et spil med den langsomste gennemsnitlige svartid', 'Speed', 'gold', 'rare', NULL),
('ACH-088', 'Fastest Finger', 'Hurtigste finger', 'Have the fastest average answer time in a Party game 10 times', 'Hav den hurtigste gennemsnitlige svartid i et Party Mode-spil 10 gange', 'Speed', 'gold', 'rare', NULL),
('ACH-121', 'Out of Comfort', 'Ud af komfortzonen', 'Win a game in the tag where your accuracy is lowest (min. 20 answered)', 'Vind et spil i det emne, hvor din svarprocent er lavest (mindst 20 besvarede)', 'Category Mastery', 'gold', 'rare', '{"type": "category_mastery_lowest", "minAnswered": 20}'::jsonb),
('ACH-123', 'First Host', 'Første vært', 'Host 1 Party Mode game', 'Vær vært for 1 spil i Party Mode', 'Social', 'bronze', 'common', NULL),
('ACH-124', 'Host with the Most', 'Den perfekte vært', 'Host 10 Party Mode games', 'Vær vært for 10 spil i Party Mode', 'Social', 'silver', 'uncommon', NULL),
('ACH-125', 'Party Planner', 'Festplanlægger', 'Host 25 Party Mode games', 'Vær vært for 25 spil i Party Mode', 'Social', 'gold', 'uncommon', NULL),
('ACH-126', 'Event Manager', 'Eventmanager', 'Host 50 Party Mode games', 'Vær vært for 50 spil i Party Mode', 'Social', 'gold', 'rare', NULL),
('ACH-127', 'Master of Ceremonies', 'Toastmaster', 'Host 100 Party Mode games', 'Vær vært for 100 spil i Party Mode', 'Social', 'platinum', 'epic', NULL),
('ACH-128', 'Full House', 'Fuldt hus', 'Play a Party game at maximum player count', 'Spil et Party Mode-spil med maksimalt antal spillere', 'Social', 'gold', 'rare', NULL),
('ACH-129', 'Crowd Pleaser', 'Publikumsmagnet', 'Host a Party game with 6 or more players', 'Vær vært for et Party Mode-spil med mindst 6 spillere', 'Social', 'silver', 'uncommon', NULL),
('ACH-130', 'Party Starter', 'Først fra start', 'Be the first player to answer correctly in a Party game', 'Vær den første spiller, der svarer rigtigt i et Party Mode-spil', 'Social', 'bronze', 'common', NULL),
('ACH-131', 'Lone Genius', 'Det ensomme geni', 'Be the only player to answer a question correctly in a game with 4+ players', 'Vær den eneste spiller, der svarer rigtigt på et spørgsmål i et spil med mindst 4 spillere', 'Social', 'gold', 'rare', NULL),
('ACH-132', 'Lone Genius x10', 'Det ensomme geni x10', 'Be the only correct player (4+ players) 10 times', 'Vær den eneste med rigtigt svar (mindst 4 spillere) 10 gange', 'Social', 'platinum', 'epic', NULL),
('ACH-133', 'Giant Slayer', 'Kæmpedræber', 'Beat the player with the highest lifetime score in the lobby', 'Slå spilleren med den højeste samlede score i lobbyen', 'Social', 'gold', 'rare', NULL),
('ACH-134', 'Recruiter', 'Hververen', 'Invite a friend who plays their first game', 'Invitér en ven, der spiller sit første spil', 'Social', 'silver', 'uncommon', NULL),
('ACH-135', 'Talent Scout', 'Talentspejder', 'Invite 5 friends who each play a game', 'Invitér 5 venner, der hver spiller et spil', 'Social', 'gold', 'rare', NULL),
('ACH-136', 'Influencer', 'Influencer', 'Invite 25 friends who each play a game', 'Invitér 25 venner, der hver spiller et spil', 'Social', 'platinum', 'epic', NULL),
('ACH-137', 'Squad Goals', 'Kliken', 'Play 10 games with the same group of 3+ people', 'Spil 10 spil med den samme gruppe på mindst 3 personer', 'Social', 'gold', 'rare', NULL),
('ACH-138', 'Ride or Die', 'Gennem tykt og tyndt', 'Play 50 games with the same group of 3+ people', 'Spil 50 spil med den samme gruppe på mindst 3 personer', 'Social', 'platinum', 'epic', NULL),
('ACH-139', 'Rivals', 'Rivaler', 'Play against the same person 25 times', 'Spil mod den samme person 25 gange', 'Social', 'gold', 'rare', NULL),
('ACH-140', 'Nemesis', 'Ærkerival', 'Play against the same person 100 times', 'Spil mod den samme person 100 gange', 'Social', 'platinum', 'epic', NULL),
('ACH-141', 'Sweet Revenge', 'Hævnen er sød', 'Beat a player who beat you in your previous game together', 'Slå en spiller, der slog dig i jeres seneste spil sammen', 'Social', 'silver', 'uncommon', NULL),
('ACH-142', 'Good Sport', 'God taber', 'Finish last but play again with the same group immediately', 'Bliv sidst – og spil straks igen med samme gruppe', 'Social', 'silver', 'uncommon', NULL),
('ACH-143', 'Welcome Committee', 'Velkomstkomité', 'Play a game with a brand-new player (first game)', 'Spil et spil med en helt ny spiller (deres første spil)', 'Social', 'silver', 'uncommon', NULL),
('ACH-144', 'Share the Glory', 'Del æren', 'Share a game result or achievement', 'Del et spilresultat eller en bedrift', 'Social', 'bronze', 'common', NULL),
('ACH-145', 'Broadcaster', 'Delekonge', 'Share 25 game results or achievements', 'Del 25 spilresultater eller bedrifter', 'Social', 'gold', 'rare', NULL),
('ACH-146', 'Point Collector', 'Pointsamler', 'Earn 10,000 lifetime points', 'Optjen 10.000 point (samlet)', 'Score', 'bronze', 'common', NULL),
('ACH-147', 'Point Stacker', 'Pointstabler', 'Earn 50,000 lifetime points', 'Optjen 50.000 point (samlet)', 'Score', 'silver', 'uncommon', NULL),
('ACH-148', 'Point Hoarder', 'Pointhamstrer', 'Earn 100,000 lifetime points', 'Optjen 100.000 point (samlet)', 'Score', 'gold', 'uncommon', NULL),
('ACH-149', 'Point Baron', 'Pointbaron', 'Earn 500,000 lifetime points', 'Optjen 500.000 point (samlet)', 'Score', 'gold', 'rare', NULL),
('ACH-150', 'Point Millionaire', 'Pointmillionær', 'Earn 1,000,000 lifetime points', 'Optjen 1.000.000 point (samlet)', 'Score', 'platinum', 'epic', NULL),
('ACH-151', 'Point Tycoon', 'Pointmogul', 'Earn 10,000,000 lifetime points', 'Optjen 10.000.000 point (samlet)', 'Score', 'diamond', 'legendary', NULL),
('ACH-152', 'Personal Best', 'Personlig rekord', 'Beat your own single-game high score', 'Slå din egen rekord for ét spil', 'Score', 'bronze', 'common', NULL),
('ACH-153', 'Overachiever', 'Overflyver', 'Beat your average score 5 games in a row', 'Slå din gennemsnitsscore 5 spil i træk', 'Score', 'gold', 'rare', NULL),
('ACH-154', 'High Roller', 'Storspiller', 'Score 10,000+ points in a single game', 'Scor mindst 10.000 point i ét spil', 'Score', 'gold', 'rare', NULL),
('ACH-155', 'Record Breaker', 'Rekordsætter', 'Set a new lobby high score in Party Mode', 'Sæt ny lobbyrekord i Party Mode', 'Score', 'gold', 'rare', NULL),
('ACH-156', 'Night Owl', 'Natugle', 'Play a game between midnight and 4 AM', 'Spil et spil mellem midnat og kl. 4', 'Calendar', 'bronze', 'common', NULL),
('ACH-157', 'Early Bird', 'Guld i mund', 'Play a game before 7 AM', 'Spil et spil før kl. 7', 'Calendar', 'bronze', 'common', NULL),
('ACH-158', 'Lunch Break Genius', 'Frokostpausens geni', 'Play between 12 and 1 PM on a weekday', 'Spil mellem kl. 12 og 13 på en hverdag', 'Calendar', 'bronze', 'common', NULL),
('ACH-159', 'Weekend Warrior', 'Weekendkriger', 'Play every Saturday and Sunday for 4 consecutive weeks', 'Spil hver lørdag og søndag i 4 uger i træk', 'Calendar', 'gold', 'rare', NULL),
('ACH-160', 'New Year, New Brain', 'Nyt år, ny hjerne', 'Play a game on January 1st', 'Spil et spil den 1. januar', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-161', 'Spooky Scholar', 'Uhyggeligt klog', 'Play a game on Halloween', 'Spil et spil til halloween', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-162', 'Holiday Spirit', 'Julestemning', 'Play a game on December 24th or 25th', 'Spil et spil den 24. eller 25. december', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-163', 'Cupid''s Quiz', 'Amors quiz', 'Play a Party game on Valentine''s Day', 'Spil et Party Mode-spil på valentinsdag', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-164', 'Fools'' Gold', 'Aprilsnar', 'Play a game on April 1st', 'Spil et spil den 1. april', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-165', 'Midsummer Mind', 'Sankthans-hjerne', 'Play a game on the summer solstice', 'Spil et spil ved sommersolhverv', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-166', 'Anniversary', 'Årsdag', 'Play on the anniversary of your account creation', 'Spil på årsdagen for din kontooprettelse', 'Calendar', 'gold', 'rare', NULL),
('ACH-167', 'Leap of Faith', 'Skudårsspring', 'Play a game on February 29th', 'Spil et spil den 29. februar', 'Calendar', 'gold', 'epic', NULL),
('ACH-168', 'Marathon', 'Maraton', 'Play 10 games in a single day', 'Spil 10 spil på én dag', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-169', 'Ultra Marathon', 'Ultramaraton', 'Play 25 games in a single day', 'Spil 25 spil på én dag', 'Calendar', 'gold', 'rare', NULL),
('ACH-170', 'Around the Clock', 'Døgnet rundt', 'Play a game in the morning, afternoon, and evening of the same day', 'Spil et spil om morgenen, om eftermiddagen og om aftenen samme dag', 'Calendar', 'silver', 'uncommon', NULL),
('ACH-171', 'Globetrotter', 'Alle døgnets timer', 'Play games in every hour of the day (lifetime, 24 different hours)', 'Spil spil i alle døgnets 24 timer (samlet)', 'Calendar', 'platinum', 'epic', NULL),
('ACH-172', 'Confidently Wrong', 'Selvsikkert forkert', 'Answer in under 2 seconds... incorrectly', 'Svar på under 2 sekunder ... forkert', 'Humor', 'bronze', 'common', NULL),
('ACH-173', 'Speed Isn''t Everything', 'Fart er ikke alt', 'Give 100 lightning-fast wrong answers (lifetime)', 'Giv 100 lynhurtige forkerte svar (samlet)', 'Humor', 'silver', 'uncommon', NULL),
('ACH-174', 'Zero Hero', 'Et rundt nul', 'Finish a full game with zero correct answers', 'Gennemfør et helt spil uden ét eneste rigtigt svar', 'Humor', 'gold', 'rare', NULL),
('ACH-175', 'So Close', 'Så tæt på', 'Lose a game by exactly 1 point', 'Tab et spil med præcis 1 point', 'Humor', 'silver', 'uncommon', NULL),
('ACH-176', 'Always the Bridesmaid', 'Evig toer', 'Finish 2nd place 10 times', 'Bliv nummer to 10 gange', 'Humor', 'gold', 'rare', NULL),
('ACH-177', 'Participation Trophy', 'Deltagerdiplom', 'Finish last 10 times (hey, you showed up!)', 'Bliv sidst 10 gange (du mødte i det mindste op!)', 'Humor', 'silver', 'uncommon', NULL),
('ACH-178', 'Rock Bottom Club', 'Bundprop', 'Finish last 50 times (we admire the persistence)', 'Bliv sidst 50 gange (vi beundrer vedholdenheden)', 'Humor', 'gold', 'rare', NULL),
('ACH-179', 'Chaos Agent', 'Kaosagent', 'Change your answer in the final second and get it right', 'Skift dit svar i sidste sekund – og ram rigtigt', 'Humor', 'silver', 'uncommon', NULL),
('ACH-180', 'Should Have Trusted Yourself', 'Du skulle have stolet på dig selv', 'Change your answer in the final second... from right to wrong', 'Skift dit svar i sidste sekund ... fra rigtigt til forkert', 'Humor', 'silver', 'uncommon', NULL),
('ACH-181', 'Coin Flipper', 'Møntkast', 'Get exactly 50% correct in a game', 'Svar præcis 50 % rigtigt i et spil', 'Humor', 'silver', 'uncommon', NULL),
('ACH-182', 'Monday Motivation', 'Mandagsmotivation', 'Win your first game of the week on a Monday', 'Vind ugens første spil på en mandag', 'Humor', 'bronze', 'common', NULL),
('ACH-184', 'The Answer to Everything', 'Svaret på alting', 'Answer your 42nd question correctly', 'Svar rigtigt på dit spørgsmål nummer 42', 'Secret', 'silver', 'uncommon', NULL),
('ACH-185', 'Perfectly Balanced', 'Perfekt balance', 'Finish a Party game where every player ties', 'Afslut et Party Mode-spil, hvor alle spillere står lige', 'Secret', 'platinum', 'epic', NULL),
('ACH-186', 'Palindrome', 'Palindrom', 'Finish a game with a palindrome score (e.g., 1221)', 'Afslut et spil med en palindromscore (fx 1221)', 'Secret', 'gold', 'rare', NULL),
('ACH-187', 'Lucky Sevens', 'Syv-syv-syv', 'Score exactly 777 points in a game', 'Scor præcis 777 point i et spil', 'Secret', 'gold', 'rare', NULL),
('ACH-188', 'Curiosity', 'Nysgerrigheden dræbte katten', 'Tap the app logo 10 times on the home screen', 'Tryk 10 gange på app-logoet på startskærmen', 'Secret', 'silver', 'uncommon', NULL),
('ACH-189', 'Reader', 'Rulletekst-læser', 'Open the credits screen and stay for 60 seconds', 'Åbn rulleteksterne og bliv i 60 sekunder', 'Secret', 'silver', 'uncommon', NULL),
('ACH-190', 'Indecisive', 'Ubeslutsom', 'Change your answer 5 times on a single question', 'Skift dit svar 5 gange på ét spørgsmål', 'Secret', 'silver', 'uncommon', NULL),
('ACH-191', 'The Streak That Wasn''t', 'Stimen der brast', 'Break a 15+ answer streak on the very last question of a game', 'Mist en stime på mindst 15 rigtige på spillets allersidste spørgsmål', 'Secret', 'gold', 'epic', NULL),
('ACH-193', 'Binary Brain', 'Binær hjerne', 'Score exactly 1024 points in a game', 'Scor præcis 1024 point i et spil', 'Secret', 'gold', 'rare', NULL),
('ACH-194', 'Sharpshooter', 'Skarpskytte', 'Achieve 75%+ accuracy over your last 100 answered questions', 'Opnå mindst 75 % rigtige svar over dine seneste 100 besvarede spørgsmål', 'Accuracy', 'silver', 'uncommon', NULL),
('ACH-195', 'Sniper', 'Finskytte', 'Achieve 85%+ accuracy over your last 100 answered questions', 'Opnå mindst 85 % rigtige svar over dine seneste 100 besvarede spørgsmål', 'Accuracy', 'gold', 'rare', NULL),
('ACH-196', 'Deadeye', 'Pletskud', 'Achieve 95%+ accuracy over your last 100 answered questions', 'Opnå mindst 95 % rigtige svar over dine seneste 100 besvarede spørgsmål', 'Accuracy', 'platinum', 'epic', NULL),
('ACH-197', 'Bounce Back', 'Ovenpå igen', 'Answer correctly right after 3 wrong answers in a row', 'Svar rigtigt lige efter 3 forkerte svar i træk', 'Accuracy', 'bronze', 'common', NULL),
('ACH-198', 'Second Half Surge', 'Stærk anden halvleg', 'Answer every question in the second half of a game correctly after missing 3+ in the first half', 'Svar rigtigt på alle spørgsmål i anden halvdel af et spil efter mindst 3 fejl i første halvdel', 'Accuracy', 'gold', 'rare', NULL),
('ACH-199', 'Explorer', 'Opdagelsesrejsende', 'Try every game mode at least once', 'Prøv alle spiltilstande mindst én gang', 'Meta', 'silver', 'uncommon', NULL),
('ACH-200', 'Profile Pro', 'Profilprof', 'Complete your profile and pick an avatar', 'Udfyld din profil og vælg en avatar', 'Meta', 'bronze', 'common', NULL),
('ACH-201', 'Stylist', 'Stilist', 'Change your avatar or theme 5 times', 'Skift avatar eller tema 5 gange', 'Meta', 'bronze', 'common', NULL),
('ACH-202', 'Settings Tinkerer', 'Indstillingsnørd', 'Customize your game settings for the first time', 'Tilpas dine spilindstillinger for første gang', 'Meta', 'bronze', 'common', NULL),
('ACH-203', 'Feedbacker', 'Feedbackgiver', 'Rate or report a question', 'Bedøm eller anmeld et spørgsmål', 'Meta', 'bronze', 'common', NULL),
('ACH-204', 'Quality Control', 'Kvalitetskontrol', 'Rate or report 100 questions', 'Bedøm eller anmeld 100 spørgsmål', 'Meta', 'gold', 'rare', NULL),
('ACH-205', 'Achievement Hunter', 'Trofæjæger', 'Unlock 10% of all achievements', 'Lås 10 % af alle bedrifter op', 'Meta', 'silver', 'uncommon', NULL),
('ACH-206', 'Trophy Case', 'Pokalskab', 'Unlock 25% of all achievements', 'Lås 25 % af alle bedrifter op', 'Meta', 'gold', 'rare', NULL),
('ACH-207', 'Decorated', 'Dekoreret', 'Unlock 50% of all achievements', 'Lås 50 % af alle bedrifter op', 'Meta', 'platinum', 'epic', NULL),
('ACH-208', 'Completionist', '100 %-klubben', 'Unlock 100% of all achievements', 'Lås alle bedrifter op', 'Meta', 'legendary', 'legendary', NULL),
('ACH-209', 'Early Adopter', 'Pioner', 'Join during the app''s first year (limited-time)', 'Opret dig i appens første leveår (tidsbegrænset)', 'Meta', 'diamond', 'legendary', NULL),
('ACH-210', 'Welcome Back', 'Velkommen tilbage', 'Return after 7+ days away', 'Vend tilbage efter mindst 7 dages pause', 'Retention', 'bronze', 'common', NULL),
('ACH-211', 'Long Time No See', 'Længe siden', 'Return after 30+ days away and win your first game back', 'Vend tilbage efter mindst 30 dages pause og vind dit første spil', 'Retention', 'gold', 'rare', NULL),
('ACH-212', 'Rust Never Sleeps', 'Rustfri', 'Get a perfect game after 14+ days away', 'Få et perfekt spil efter mindst 14 dages pause', 'Retention', 'platinum', 'epic', NULL),
('ACH-213', 'Hard Mode Curious', 'Svær tilstand: nybegynder', 'Play 1 game on the hardest difficulty', 'Spil 1 spil på sværeste sværhedsgrad', 'Difficulty', 'bronze', 'common', NULL),
('ACH-214', 'Hard Mode Regular', 'Svær tilstand: stamgæst', 'Play 25 games on the hardest difficulty', 'Spil 25 spil på sværeste sværhedsgrad', 'Difficulty', 'silver', 'uncommon', NULL),
('ACH-215', 'Hard Mode Veteran', 'Svær tilstand: veteran', 'Play 100 games on the hardest difficulty', 'Spil 100 spil på sværeste sværhedsgrad', 'Difficulty', 'gold', 'rare', NULL),
('ACH-216', 'No Sweat', 'Uden sved på panden', 'Win a game on the hardest difficulty', 'Vind et spil på sværeste sværhedsgrad', 'Difficulty', 'gold', 'rare', NULL),
('ACH-217', 'Masochist', 'Masochist', 'Get a perfect game on the hardest difficulty', 'Få et perfekt spil på sværeste sværhedsgrad', 'Difficulty', 'diamond', 'legendary', NULL),
('ACH-218', 'Popcorn Rookie', 'Popcorn-begynder', 'Answer 25 ''movies'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om film (samlet)', 'movies', 'bronze', 'common', NULL),
('ACH-219', 'Movie Buff', 'Filmnørd', 'Answer 100 ''movies'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om film (samlet)', 'movies', 'silver', 'uncommon', NULL),
('ACH-220', 'Film Fanatic', 'Filmfanatiker', 'Answer 250 ''movies'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om film (samlet)', 'movies', 'gold', 'rare', NULL),
('ACH-221', 'Cinema Scholar', 'Filmekspert', 'Answer 500 ''movies'' questions correctly (lifetime)', 'Svar rigtigt på 500 spørgsmål om film (samlet)', 'movies', 'platinum', 'epic', NULL),
('ACH-222', 'Silver Screen Legend', 'Lærredets legende', 'Answer 1,000 ''movies'' questions correctly (lifetime)', 'Svar rigtigt på 1.000 spørgsmål om film (samlet)', 'movies', 'diamond', 'legendary', NULL),
('ACH-223', 'Critic''s Eye', 'Kritikerens blik', 'Achieve 90%+ accuracy on ''movies'' over 200+ answered questions', 'Opnå mindst 90 % rigtige svar om film over mindst 200 besvarede spørgsmål', 'movies', 'diamond', 'legendary', NULL),
('ACH-224', 'Night at the Movies', 'Filmaften', 'Answer 25 movies questions correctly in one day', 'Svar rigtigt på 25 spørgsmål om film på én dag', 'movies', 'gold', 'rare', NULL),
('ACH-225', 'Hygge Beginner', 'Hyggebegynder', 'Answer 25 ''danish-culture'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om dansk kultur (samlet)', 'danish-culture', 'bronze', 'common', NULL),
('ACH-226', 'Dannebrog Devotee', 'Dannebrogsbærer', 'Answer 100 ''danish-culture'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om dansk kultur (samlet)', 'danish-culture', 'silver', 'uncommon', NULL),
('ACH-227', 'Smørrebrød Scholar', 'Smørrebrødsekspert', 'Answer 250 ''danish-culture'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om dansk kultur (samlet)', 'danish-culture', 'gold', 'rare', NULL),
('ACH-228', 'True Dane', 'Ægte dansker', 'Answer 500 ''danish-culture'' questions correctly (lifetime)', 'Svar rigtigt på 500 spørgsmål om dansk kultur (samlet)', 'danish-culture', 'platinum', 'epic', NULL),
('ACH-229', 'National Treasure', 'Nationalklenodie', 'Answer 1,000 ''danish-culture'' questions correctly (lifetime)', 'Svar rigtigt på 1.000 spørgsmål om dansk kultur (samlet)', 'danish-culture', 'diamond', 'legendary', NULL),
('ACH-230', 'Danish Design', 'Dansk design', 'Achieve 90%+ accuracy on ''danish-culture'' over 200+ answered questions', 'Opnå mindst 90 % rigtige svar om dansk kultur over mindst 200 besvarede spørgsmål', 'danish-culture', 'diamond', 'legendary', NULL),
('ACH-231', 'Grundlovsdag', 'Grundlovsdag', 'Answer a danish-culture question correctly on June 5th (Constitution Day)', 'Svar rigtigt på et spørgsmål om dansk kultur den 5. juni (grundlovsdag)', 'danish-culture', 'gold', 'rare', NULL),
('ACH-232', 'Headline Reader', 'Overskriftslæser', 'Answer 25 ''current-events'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om aktuelle emner (samlet)', 'current-events', 'bronze', 'common', NULL),
('ACH-233', 'News Junkie', 'Nyhedsjunkie', 'Answer 100 ''current-events'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om aktuelle emner (samlet)', 'current-events', 'silver', 'uncommon', NULL),
('ACH-234', 'Well Informed', 'Velinformeret', 'Answer 250 ''current-events'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om aktuelle emner (samlet)', 'current-events', 'gold', 'rare', NULL),
('ACH-235', 'Finger on the Pulse', 'Fingeren på pulsen', 'Answer 400 ''current-events'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om aktuelle emner (samlet)', 'current-events', 'platinum', 'epic', NULL),
('ACH-236', 'Fact Checker', 'Faktatjekker', 'Achieve 90%+ accuracy on ''current-events'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om aktuelle emner over mindst 100 besvarede spørgsmål', 'current-events', 'diamond', 'legendary', NULL),
('ACH-237', 'Channel Surfer', 'Kanalsurfer', 'Answer 25 ''tv-shows'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om tv-serier (samlet)', 'tv-shows', 'bronze', 'common', NULL),
('ACH-238', 'Binge Watcher', 'Seriesluger', 'Answer 100 ''tv-shows'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om tv-serier (samlet)', 'tv-shows', 'silver', 'uncommon', NULL),
('ACH-239', 'Series Regular', 'Fast på rollelisten', 'Answer 250 ''tv-shows'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om tv-serier (samlet)', 'tv-shows', 'gold', 'rare', NULL),
('ACH-240', 'Showrunner', 'Showrunner', 'Answer 400 ''tv-shows'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om tv-serier (samlet)', 'tv-shows', 'platinum', 'epic', NULL),
('ACH-241', 'Golden Age', 'Guldalder', 'Achieve 90%+ accuracy on ''tv-shows'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om tv-serier over mindst 100 besvarede spørgsmål', 'tv-shows', 'diamond', 'legendary', NULL),
('ACH-242', 'Humming Along', 'Nynner med', 'Answer 25 ''music'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om musik (samlet)', 'music', 'bronze', 'common', NULL),
('ACH-243', 'Playlist Pro', 'Playlisteprof', 'Answer 100 ''music'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om musik (samlet)', 'music', 'silver', 'uncommon', NULL),
('ACH-244', 'Chart Topper', 'Hitlistetopper', 'Answer 250 ''music'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om musik (samlet)', 'music', 'gold', 'rare', NULL),
('ACH-245', 'Grand Maestro', 'Maestro', 'Answer 400 ''music'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om musik (samlet)', 'music', 'platinum', 'epic', NULL),
('ACH-246', 'Perfect Pitch', 'Absolut gehør', 'Achieve 90%+ accuracy on ''music'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om musik over mindst 100 besvarede spørgsmål', 'music', 'diamond', 'legendary', NULL),
('ACH-247', 'Pet Lover', 'Dyreven', 'Answer 25 ''animals'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om dyr (samlet)', 'animals', 'bronze', 'common', NULL),
('ACH-248', 'Zookeeper', 'Dyrepasser', 'Answer 100 ''animals'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om dyr (samlet)', 'animals', 'silver', 'uncommon', NULL),
('ACH-249', 'Wildlife Expert', 'Naturekspert', 'Answer 250 ''animals'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om dyr (samlet)', 'animals', 'gold', 'rare', NULL),
('ACH-250', 'Animal Whisperer', 'Dyrehvisker', 'Answer 400 ''animals'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om dyr (samlet)', 'animals', 'platinum', 'epic', NULL),
('ACH-251', 'Apex Predator', 'Toprovdyr', 'Achieve 90%+ accuracy on ''animals'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om dyr over mindst 100 besvarede spørgsmål', 'animals', 'diamond', 'legendary', NULL),
('ACH-252', 'Taste Tester', 'Smagsdommer', 'Answer 25 ''food-drink'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om mad og drikke (samlet)', 'food-drink', 'bronze', 'common', NULL),
('ACH-253', 'Foodie', 'Madglad', 'Answer 100 ''food-drink'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om mad og drikke (samlet)', 'food-drink', 'silver', 'uncommon', NULL),
('ACH-254', 'Gourmet', 'Gourmet', 'Answer 250 ''food-drink'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om mad og drikke (samlet)', 'food-drink', 'gold', 'rare', NULL),
('ACH-255', 'Michelin Mind', 'Michelin-hjerne', 'Answer 400 ''food-drink'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om mad og drikke (samlet)', 'food-drink', 'platinum', 'epic', NULL),
('ACH-256', 'Head Chef', 'Køkkenchef', 'Achieve 90%+ accuracy on ''food-drink'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om mad og drikke over mindst 100 besvarede spørgsmål', 'food-drink', 'diamond', 'legendary', NULL),
('ACH-257', 'Time Tourist', 'Tidsturist', 'Answer 25 ''history'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om historie (samlet)', 'history', 'bronze', 'common', NULL),
('ACH-258', 'History Buff', 'Historienørd', 'Answer 100 ''history'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om historie (samlet)', 'history', 'silver', 'uncommon', NULL),
('ACH-259', 'Archivist', 'Arkivar', 'Answer 250 ''history'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om historie (samlet)', 'history', 'gold', 'rare', NULL),
('ACH-260', 'Keeper of Ages', 'Tidens vogter', 'Answer 400 ''history'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om historie (samlet)', 'history', 'platinum', 'epic', NULL),
('ACH-261', 'Primary Source', 'Primærkilde', 'Achieve 90%+ accuracy on ''history'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om historie over mindst 100 besvarede spørgsmål', 'history', 'diamond', 'legendary', NULL),
('ACH-262', 'Coin Flip', 'Plat eller krone', 'Answer 25 ''true-false'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om sandt/falsk (samlet)', 'true-false', 'bronze', 'common', NULL),
('ACH-263', 'Truth Seeker', 'Sandhedssøger', 'Answer 100 ''true-false'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om sandt/falsk (samlet)', 'true-false', 'silver', 'uncommon', NULL),
('ACH-264', 'Lie Detector', 'Løgnedetektor', 'Answer 250 ''true-false'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om sandt/falsk (samlet)', 'true-false', 'gold', 'rare', NULL),
('ACH-265', 'Human Polygraph', 'Sandhedsvidne', 'Answer 400 ''true-false'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om sandt/falsk (samlet)', 'true-false', 'platinum', 'epic', NULL),
('ACH-266', 'No Hesitation', 'Uden tøven', 'Achieve 90%+ accuracy on ''true-false'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om sandt/falsk over mindst 100 besvarede spørgsmål', 'true-false', 'diamond', 'legendary', NULL),
('ACH-267', 'Star Spotter', 'Stjernespotter', 'Answer 25 ''celebrities'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om kendte (samlet)', 'celebrities', 'bronze', 'common', NULL),
('ACH-268', 'Gossip Guru', 'Sladderguru', 'Answer 100 ''celebrities'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om kendte (samlet)', 'celebrities', 'silver', 'uncommon', NULL),
('ACH-269', 'Red Carpet Regular', 'Fast på den røde løber', 'Answer 250 ''celebrities'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om kendte (samlet)', 'celebrities', 'gold', 'rare', NULL),
('ACH-270', 'A-Lister', 'A-kendis', 'Answer 400 ''celebrities'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om kendte (samlet)', 'celebrities', 'platinum', 'epic', NULL),
('ACH-271', 'Front Row Seat', 'På første række', 'Achieve 90%+ accuracy on ''celebrities'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om kendte over mindst 100 besvarede spørgsmål', 'celebrities', 'diamond', 'legendary', NULL),
('ACH-272', 'Curious Mind', 'Forskerspire', 'Answer 25 ''science'' questions correctly (lifetime)', 'Svar rigtigt på 25 spørgsmål om videnskab (samlet)', 'science', 'bronze', 'common', NULL),
('ACH-273', 'Lab Assistant', 'Laborant', 'Answer 100 ''science'' questions correctly (lifetime)', 'Svar rigtigt på 100 spørgsmål om videnskab (samlet)', 'science', 'silver', 'uncommon', NULL),
('ACH-274', 'Lead Researcher', 'Forskningsleder', 'Answer 250 ''science'' questions correctly (lifetime)', 'Svar rigtigt på 250 spørgsmål om videnskab (samlet)', 'science', 'gold', 'rare', NULL),
('ACH-275', 'Nobel Material', 'Nobelkandidat', 'Answer 400 ''science'' questions correctly (lifetime)', 'Svar rigtigt på 400 spørgsmål om videnskab (samlet)', 'science', 'platinum', 'epic', NULL),
('ACH-276', 'Peer Reviewed', 'Fagfællebedømt', 'Achieve 90%+ accuracy on ''science'' over 100+ answered questions', 'Opnå mindst 90 % rigtige svar om videnskab over mindst 100 besvarede spørgsmål', 'science', 'diamond', 'legendary', NULL),
('ACH-277', 'Riddle Rookie', 'Gådebegynder', 'Answer 15 ''riddles'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om gåder (samlet)', 'riddles', 'bronze', 'common', NULL),
('ACH-278', 'Puzzle Solver', 'Gådeløser', 'Answer 50 ''riddles'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om gåder (samlet)', 'riddles', 'silver', 'uncommon', NULL),
('ACH-279', 'Sphinx', 'Sfinks', 'Answer 120 ''riddles'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om gåder (samlet)', 'riddles', 'gold', 'rare', NULL),
('ACH-280', 'Enigma', 'Enigma', 'Answer 10 riddles correctly in a row', 'Svar rigtigt på 10 gåder i træk', 'riddles', 'gold', 'rare', NULL),
('ACH-281', 'Map Reader', 'Kortlæser', 'Answer 15 ''geography'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om geografi (samlet)', 'geography', 'bronze', 'common', NULL),
('ACH-282', 'Cartographer', 'Kartograf', 'Answer 50 ''geography'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om geografi (samlet)', 'geography', 'silver', 'uncommon', NULL),
('ACH-283', 'Living Atlas', 'Levende atlas', 'Answer 120 ''geography'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om geografi (samlet)', 'geography', 'gold', 'rare', NULL),
('ACH-284', 'Compass Rose', 'Kompasrose', 'Achieve 90%+ accuracy on geography over 60+ questions', 'Opnå mindst 90 % rigtige svar om geografi over mindst 60 spørgsmål', 'geography', 'gold', 'rare', NULL),
('ACH-285', 'Wish Upon a Quiz', 'Ønskebrønden', 'Answer 15 ''disney'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om Disney (samlet)', 'disney', 'bronze', 'common', NULL),
('ACH-286', 'Disney Devotee', 'Disney-fan', 'Answer 50 ''disney'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om Disney (samlet)', 'disney', 'silver', 'uncommon', NULL),
('ACH-287', 'Magic Kingdom Mind', 'Magisk viden', 'Answer 120 ''disney'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om Disney (samlet)', 'disney', 'gold', 'rare', NULL),
('ACH-288', 'Fairy Tale Ending', 'Eventyrlig slutning', 'Get every disney question in a game correct', 'Svar rigtigt på alle Disney-spørgsmål i ét spil', 'disney', 'gold', 'rare', NULL),
('ACH-289', 'Bookworm', 'Bogorm', 'Answer 15 ''books'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om bøger (samlet)', 'books', 'bronze', 'common', NULL),
('ACH-290', 'Librarian', 'Bibliotekar', 'Answer 50 ''books'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om bøger (samlet)', 'books', 'silver', 'uncommon', NULL),
('ACH-291', 'Literary Legend', 'Litterær legende', 'Answer 120 ''books'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om bøger (samlet)', 'books', 'gold', 'rare', NULL),
('ACH-292', 'Speed Reader', 'Hurtiglæser', 'Answer 10 books questions correctly in under 4 seconds each', 'Svar rigtigt på 10 spørgsmål om bøger på under 4 sekunder hver', 'books', 'gold', 'rare', NULL),
('ACH-293', 'Elf in Training', 'Nissepraktikant', 'Answer 15 ''christmas'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om jul (samlet)', 'christmas', 'bronze', 'common', NULL),
('ACH-294', 'Santa''s Helper', 'Julemandens hjælper', 'Answer 50 ''christmas'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om jul (samlet)', 'christmas', 'silver', 'uncommon', NULL),
('ACH-295', 'Spirit of Christmas', 'Julens ånd', 'Answer 120 ''christmas'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om jul (samlet)', 'christmas', 'gold', 'rare', NULL),
('ACH-296', 'December Devotion', 'Jul til jul', 'Answer a christmas question correctly on December 24th or 25th', 'Svar rigtigt på et julespørgsmål den 24. eller 25. december', 'christmas', 'gold', 'rare', NULL),
('ACH-297', 'Benchwarmer', 'Bænkevarmer', 'Answer 15 ''sports'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om sport (samlet)', 'sports', 'bronze', 'common', NULL),
('ACH-298', 'Starting Lineup', 'I startopstillingen', 'Answer 50 ''sports'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om sport (samlet)', 'sports', 'silver', 'uncommon', NULL),
('ACH-299', 'Hall of Famer', 'Hall of Fame', 'Answer 120 ''sports'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om sport (samlet)', 'sports', 'gold', 'rare', NULL),
('ACH-300', 'Hat Trick', 'Hattrick', 'Answer 3 sports questions correctly in under 3 seconds each in one game', 'Svar rigtigt på 3 sportsspørgsmål på under 3 sekunder hver i ét spil', 'sports', 'gold', 'rare', NULL),
('ACH-301', 'Word Curious', 'Ordnysgerrig', 'Answer 15 ''language'' questions correctly (lifetime)', 'Svar rigtigt på 15 spørgsmål om sprog (samlet)', 'language', 'bronze', 'common', NULL),
('ACH-302', 'Budding Polyglot', 'Sprogtalent', 'Answer 50 ''language'' questions correctly (lifetime)', 'Svar rigtigt på 50 spørgsmål om sprog (samlet)', 'language', 'silver', 'uncommon', NULL),
('ACH-303', 'Master Linguist', 'Sprogmester', 'Answer 120 ''language'' questions correctly (lifetime)', 'Svar rigtigt på 120 spørgsmål om sprog (samlet)', 'language', 'gold', 'rare', NULL),
('ACH-304', 'Silver Tongue', 'Sølvtunge', 'Achieve 90%+ accuracy on language over 40+ questions', 'Opnå mindst 90 % rigtige svar om sprog over mindst 40 spørgsmål', 'language', 'gold', 'rare', NULL),
('ACH-305', 'Button Masher', 'Knapmaser', 'Answer 10 ''video-games'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om computerspil (samlet)', 'video-games', 'bronze', 'common', NULL),
('ACH-306', 'High Scorer', 'Highscore-jæger', 'Answer 35 ''video-games'' questions correctly (lifetime)', 'Svar rigtigt på 35 spørgsmål om computerspil (samlet)', 'video-games', 'silver', 'uncommon', NULL),
('ACH-307', 'Speedrunner', 'Speedrunner', 'Answer 5 video-games questions correctly in under 3 seconds each (lifetime)', 'Svar rigtigt på 5 spørgsmål om computerspil på under 3 sekunder hver (samlet)', 'video-games', 'gold', 'rare', NULL),
('ACH-308', 'Number Cruncher', 'Talknuser', 'Answer 10 ''math'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om matematik (samlet)', 'math', 'bronze', 'common', NULL),
('ACH-309', 'Human Calculator', 'Menneskelig lommeregner', 'Answer 34 ''math'' questions correctly (lifetime)', 'Svar rigtigt på 34 spørgsmål om matematik (samlet)', 'math', 'silver', 'uncommon', NULL),
('ACH-310', 'Prime Time', 'I den syvende himmel', 'Answer 7 math questions correctly in a row', 'Svar rigtigt på 7 matematikspørgsmål i træk', 'math', 'gold', 'rare', NULL),
('ACH-311', 'Stargazer', 'Stjernekigger', 'Answer 10 ''space'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om rummet (samlet)', 'space', 'bronze', 'common', NULL),
('ACH-312', 'Astronaut', 'Astronaut', 'Answer 32 ''space'' questions correctly (lifetime)', 'Svar rigtigt på 32 spørgsmål om rummet (samlet)', 'space', 'silver', 'uncommon', NULL),
('ACH-313', 'Moonshot', 'Månelanding', 'Get every space question in a game correct', 'Svar rigtigt på alle spørgsmål om rummet i ét spil', 'space', 'gold', 'rare', NULL),
('ACH-314', 'Med Student', 'Medicinstuderende', 'Answer 10 ''anatomy'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om anatomi (samlet)', 'anatomy', 'bronze', 'common', NULL),
('ACH-315', 'Chief Surgeon', 'Overlæge', 'Answer 32 ''anatomy'' questions correctly (lifetime)', 'Svar rigtigt på 32 spørgsmål om anatomi (samlet)', 'anatomy', 'silver', 'uncommon', NULL),
('ACH-316', 'Steady Hands', 'Sikker hånd', 'Achieve 90%+ accuracy on anatomy over 30+ questions', 'Opnå mindst 90 % rigtige svar om anatomi over mindst 30 spørgsmål', 'anatomy', 'gold', 'rare', NULL),
('ACH-317', 'Cell Mate', 'Cellekammerat', 'Answer 10 ''biology'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om biologi (samlet)', 'biology', 'bronze', 'common', NULL),
('ACH-318', 'Field Biologist', 'Feltbiolog', 'Answer 31 ''biology'' questions correctly (lifetime)', 'Svar rigtigt på 31 spørgsmål om biologi (samlet)', 'biology', 'silver', 'uncommon', NULL),
('ACH-319', 'Natural Selection', 'Naturlig selektion', 'Answer 8 biology questions correctly in a row', 'Svar rigtigt på 8 biologispørgsmål i træk', 'biology', 'gold', 'rare', NULL),
('ACH-320', 'First-Time Voter', 'Førstegangsvælger', 'Answer 10 ''politics'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om politik (samlet)', 'politics', 'bronze', 'common', NULL),
('ACH-321', 'Statesman', 'Statsmand', 'Answer 27 ''politics'' questions correctly (lifetime)', 'Svar rigtigt på 27 spørgsmål om politik (samlet)', 'politics', 'silver', 'uncommon', NULL),
('ACH-322', 'Majority Whip', 'Folketingsflertal', 'Achieve 90%+ accuracy on politics over 25+ questions', 'Opnå mindst 90 % rigtige svar om politik over mindst 25 spørgsmål', 'politics', 'gold', 'rare', NULL),
('ACH-323', 'Comic Collector', 'Tegneseriesamler', 'Answer 10 ''comics'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om tegneserier (samlet)', 'comics', 'bronze', 'common', NULL),
('ACH-324', 'Panel Expert', 'Tegneserieekspert', 'Answer 26 ''comics'' questions correctly (lifetime)', 'Svar rigtigt på 26 spørgsmål om tegneserier (samlet)', 'comics', 'silver', 'uncommon', NULL),
('ACH-325', 'Origin Story', 'Oprindelseshistorie', 'Answer your very first comics question correctly', 'Svar rigtigt på dit allerførste tegneseriespørgsmål', 'comics', 'gold', 'rare', NULL),
('ACH-326', 'First Year', 'Førsteårselev', 'Answer 10 ''harry-potter'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om Harry Potter (samlet)', 'harry-potter', 'bronze', 'common', NULL),
('ACH-327', 'Head of House', 'Præfekt', 'Answer 26 ''harry-potter'' questions correctly (lifetime)', 'Svar rigtigt på 26 spørgsmål om Harry Potter (samlet)', 'harry-potter', 'silver', 'uncommon', NULL),
('ACH-328', 'Top of the Class', 'Klassens duks', 'Get every harry-potter question in a game correct', 'Svar rigtigt på alle Harry Potter-spørgsmål i ét spil', 'harry-potter', 'gold', 'rare', NULL),
('ACH-329', 'Myth Curious', 'Mytenysgerrig', 'Answer 10 ''mythology'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om mytologi (samlet)', 'mythology', 'bronze', 'common', NULL),
('ACH-330', 'Demigod', 'Halvgud', 'Answer 24 ''mythology'' questions correctly (lifetime)', 'Svar rigtigt på 24 spørgsmål om mytologi (samlet)', 'mythology', 'silver', 'uncommon', NULL),
('ACH-331', 'Seat on Olympus', 'Plads på Olympen', 'Answer 8 mythology questions correctly in a row', 'Svar rigtigt på 8 mytologispørgsmål i træk', 'mythology', 'gold', 'rare', NULL),
('ACH-332', 'Sunday League', 'Serie 5-spiller', 'Answer 10 ''football'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om fodbold (samlet)', 'football', 'bronze', 'common', NULL),
('ACH-333', 'Golden Boot', 'Guldstøvlen', 'Answer 23 ''football'' questions correctly (lifetime)', 'Svar rigtigt på 23 spørgsmål om fodbold (samlet)', 'football', 'silver', 'uncommon', NULL),
('ACH-334', 'Top Corner', 'Oppe i krogen', 'Answer 5 football questions correctly in under 3 seconds each (lifetime)', 'Svar rigtigt på 5 fodboldspørgsmål på under 3 sekunder hver (samlet)', 'football', 'gold', 'rare', NULL),
('ACH-335', 'Marvel Recruit', 'Marvel-rekrut', 'Answer 10 ''marvel'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om Marvel (samlet)', 'marvel', 'bronze', 'common', NULL),
('ACH-336', 'Marvel Veteran', 'Marvel-veteran', 'Answer 21 ''marvel'' questions correctly (lifetime)', 'Svar rigtigt på 21 spørgsmål om Marvel (samlet)', 'marvel', 'silver', 'uncommon', NULL),
('ACH-337', 'Assembled', 'Tropperne er samlet', 'Answer 6 marvel questions correctly in a row', 'Svar rigtigt på 6 Marvel-spørgsmål i træk', 'marvel', 'gold', 'rare', NULL),
('ACH-338', 'Courtier', 'Hofmand', 'Answer 10 ''royalty'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om kongelige (samlet)', 'royalty', 'bronze', 'common', NULL),
('ACH-339', 'Crown Jewel', 'Kronjuvel', 'Answer 20 ''royalty'' questions correctly (lifetime)', 'Svar rigtigt på 20 spørgsmål om kongelige (samlet)', 'royalty', 'silver', 'uncommon', NULL),
('ACH-340', 'Royal Decree', 'Kongeligt dekret', 'Achieve 90%+ accuracy on royalty over 20+ questions', 'Opnå mindst 90 % rigtige svar om kongelige over mindst 20 spørgsmål', 'royalty', 'gold', 'rare', NULL),
('ACH-341', 'Sidekick', 'Sidekick', 'Answer 10 ''superheroes'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om superhelte (samlet)', 'superheroes', 'bronze', 'common', NULL),
('ACH-342', 'Hero of the City', 'Byens helt', 'Answer 20 ''superheroes'' questions correctly (lifetime)', 'Svar rigtigt på 20 spørgsmål om superhelte (samlet)', 'superheroes', 'silver', 'uncommon', NULL),
('ACH-343', 'Secret Identity', 'Hemmelig identitet', 'Answer a superheroes question correctly between midnight and 4 AM', 'Svar rigtigt på et superhelte-spørgsmål mellem midnat og kl. 4', 'superheroes', 'gold', 'rare', NULL),
('ACH-344', 'Gotham Rookie', 'Gotham-begynder', 'Answer 10 ''batman'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om Batman (samlet)', 'batman', 'bronze', 'common', NULL),
('ACH-345', 'Gotham Guardian', 'Gothams vogter', 'Answer 19 ''batman'' questions correctly (lifetime)', 'Svar rigtigt på 19 spørgsmål om Batman (samlet)', 'batman', 'silver', 'uncommon', NULL),
('ACH-346', 'Night Shift', 'Nattevagt', 'Answer a batman question correctly after 10 PM', 'Svar rigtigt på et Batman-spørgsmål efter kl. 22', 'batman', 'gold', 'rare', NULL),
('ACH-347', 'Learner''s Permit', 'Kørekort på prøve', 'Answer 10 ''cars'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om biler (samlet)', 'cars', 'bronze', 'common', NULL),
('ACH-348', 'Gearhead', 'Benzin i blodet', 'Answer 17 ''cars'' questions correctly (lifetime)', 'Svar rigtigt på 17 spørgsmål om biler (samlet)', 'cars', 'silver', 'uncommon', NULL),
('ACH-349', 'Pole Position', 'Pole position', 'Be the fastest correct answer on a cars question in Party Mode', 'Vær hurtigst med det rigtige svar på et bilspørgsmål i Party Mode', 'cars', 'gold', 'rare', NULL),
('ACH-350', 'History Cadet', 'Historiekadet', 'Answer 10 ''world-war-2'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om 2. verdenskrig (samlet)', 'world-war-2', 'bronze', 'common', NULL),
('ACH-351', 'WW2 Historian', 'Krigshistoriker', 'Answer 17 ''world-war-2'' questions correctly (lifetime)', 'Svar rigtigt på 17 spørgsmål om 2. verdenskrig (samlet)', 'world-war-2', 'silver', 'uncommon', NULL),
('ACH-352', 'War Correspondent', 'Krigskorrespondent', 'Achieve 90%+ accuracy on world-war-2 over 18+ questions', 'Opnå mindst 90 % rigtige svar om 2. verdenskrig over mindst 18 spørgsmål', 'world-war-2', 'gold', 'rare', NULL),
('ACH-353', 'Beta Tester', 'Betatester', 'Answer 10 ''technology'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om teknologi (samlet)', 'technology', 'bronze', 'common', NULL),
('ACH-354', 'Tech Support', 'IT-supporter', 'Answer 16 ''technology'' questions correctly (lifetime)', 'Svar rigtigt på 16 spørgsmål om teknologi (samlet)', 'technology', 'silver', 'uncommon', NULL),
('ACH-355', 'Debugger', 'Fejlfinder', 'Answer 5 technology questions correctly in a row', 'Svar rigtigt på 5 teknologispørgsmål i træk', 'technology', 'gold', 'rare', NULL),
('ACH-356', 'Pun Apprentice', 'Ordspilslærling', 'Answer 10 ''wordplay'' questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om ordspil (samlet)', 'wordplay', 'bronze', 'common', NULL),
('ACH-357', 'Pun Intended', 'Ordekvilibrist', 'Answer 16 ''wordplay'' questions correctly (lifetime)', 'Svar rigtigt på 16 spørgsmål om ordspil (samlet)', 'wordplay', 'silver', 'uncommon', NULL),
('ACH-358', 'Wordsmith', 'Ordsmed', 'Answer 5 wordplay questions correctly in a row', 'Svar rigtigt på 5 ordspilsspørgsmål i træk', 'wordplay', 'gold', 'rare', NULL),
('ACH-359', 'Cosmopolitan', 'Cosmopolitan', 'Answer 12 sex-and-the-city questions correctly (lifetime)', 'Svar rigtigt på 12 spørgsmål om Sex and the City (samlet)', 'sex-and-the-city', 'silver', 'uncommon', NULL),
('ACH-360', 'Mixologist', 'Mixolog', 'Answer 12 cocktails questions correctly (lifetime)', 'Svar rigtigt på 12 spørgsmål om cocktails (samlet)', 'cocktails', 'silver', 'uncommon', NULL),
('ACH-361', 'Shield Bearer', 'Skjoldbærer', 'Answer 6 vikings questions correctly (lifetime)', 'Svar rigtigt på 6 spørgsmål om vikinger (samlet)', 'vikings', 'silver', 'uncommon', NULL),
('ACH-362', 'Jarl of Trivia', 'Quizjarl', 'Answer 13 vikings questions correctly (lifetime)', 'Svar rigtigt på 13 spørgsmål om vikinger (samlet)', 'vikings', 'silver', 'uncommon', NULL),
('ACH-363', 'True Crime Fan', 'True crime-fan', 'Answer 10 crime-news questions correctly (lifetime)', 'Svar rigtigt på 10 spørgsmål om kriminalstof (samlet)', 'crime-news', 'silver', 'uncommon', NULL),
('ACH-364', 'Star Pilot', 'Stjernepilot', 'Answer 9 star-wars questions correctly (lifetime)', 'Svar rigtigt på 9 spørgsmål om Star Wars (samlet)', 'star-wars', 'silver', 'uncommon', NULL),
('ACH-365', 'Trendsetter', 'Trendsætter', 'Answer 7 fashion questions correctly (lifetime)', 'Svar rigtigt på 7 spørgsmål om mode (samlet)', 'fashion', 'silver', 'uncommon', NULL),
('ACH-366', 'Storm Chaser', 'Stormjæger', 'Answer 6 weather questions correctly (lifetime)', 'Svar rigtigt på 6 spørgsmål om vejr (samlet)', 'weather', 'silver', 'uncommon', NULL),
('ACH-367', 'Brand Ambassador', 'Mærkevareekspert', 'Answer 5 brands questions correctly (lifetime)', 'Svar rigtigt på 5 spørgsmål om mærkevarer (samlet)', 'brands', 'silver', 'uncommon', NULL),
('ACH-368', 'Gold Medalist', 'OL-guld', 'Answer 4 olympics questions correctly (lifetime)', 'Svar rigtigt på 4 spørgsmål om OL (samlet)', 'olympics', 'silver', 'uncommon', NULL),
('ACH-369', 'Theologian', 'Teolog', 'Answer 4 religion questions correctly (lifetime)', 'Svar rigtigt på 4 spørgsmål om religion (samlet)', 'religion', 'silver', 'uncommon', NULL),
('ACH-370', 'Trekker', 'Trekkie', 'Answer 4 star-trek questions correctly (lifetime)', 'Svar rigtigt på 4 spørgsmål om Star Trek (samlet)', 'star-trek', 'silver', 'uncommon', NULL),
('ACH-371', 'Roll the Dice', 'Terningerne er kastet', 'Answer all 3 board-games questions correctly (lifetime)', 'Svar rigtigt på alle 3 spørgsmål om brætspil (samlet)', 'board-games', 'silver', 'uncommon', NULL),
('ACH-372', 'Game On', 'Spillet er i gang', 'Answer all 3 games questions correctly (lifetime)', 'Svar rigtigt på alle 3 spørgsmål om spil (samlet)', 'games', 'silver', 'uncommon', NULL),
('ACH-373', 'Calendar Keeper', 'Kalendervogter', 'Answer all 3 holidays questions correctly (lifetime)', 'Svar rigtigt på alle 3 spørgsmål om helligdage (samlet)', 'holidays', 'silver', 'uncommon', NULL),
('ACH-374', 'Drill Sergeant', 'Sergent', 'Answer all 3 military questions correctly (lifetime)', 'Svar rigtigt på alle 3 spørgsmål om militær (samlet)', 'military', 'silver', 'uncommon', NULL),
('ACH-375', 'Handy', 'Handyman', 'Answer all 3 tools questions correctly (lifetime)', 'Svar rigtigt på alle 3 spørgsmål om værktøj (samlet)', 'tools', 'silver', 'uncommon', NULL),
('ACH-376', 'Pop Culture Titan', 'Popkultur-titan', 'Answer 500 questions correctly across movies, tv-shows, music and celebrities', 'Svar rigtigt på 500 spørgsmål på tværs af film, tv-serier, musik og kendte', 'Cross-Tag', 'platinum', 'epic', NULL),
('ACH-377', 'Screen & Sound', 'Skærm og lyd', 'Answer 250 questions correctly across movies, tv-shows and music', 'Svar rigtigt på 250 spørgsmål på tværs af film, tv-serier og musik', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-378', 'Awards Season', 'Prisregn', 'In one day, answer correctly in movies, tv-shows, music and celebrities', 'Svar rigtigt inden for film, tv-serier, musik og kendte på én dag', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-379', 'Geek Week', 'Nørdeuge', 'Answer 50 questions correctly across comics, superheroes, marvel, batman, star-wars, star-trek, harry-potter and video-games', 'Svar rigtigt på 50 spørgsmål på tværs af tegneserier, superhelte, Marvel, Batman, Star Wars, Star Trek, Harry Potter og computerspil', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-380', 'Superfan Trifecta', 'Heltetrio', 'Answer correctly in marvel, batman and superheroes in a single day', 'Svar rigtigt inden for Marvel, Batman og superhelte på én dag', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-381', 'Franchise Hopper', 'Univershopper', 'Answer correctly in disney, harry-potter, star-wars and star-trek (lifetime)', 'Svar rigtigt inden for Disney, Harry Potter, Star Wars og Star Trek (samlet)', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-382', 'Multiverse Master', 'Multiversets mester', 'Answer 100 questions correctly across marvel, batman, comics and superheroes', 'Svar rigtigt på 100 spørgsmål på tværs af Marvel, Batman, tegneserier og superhelte', 'Cross-Tag', 'platinum', 'epic', NULL),
('ACH-383', 'STEM Star', 'Naturfagsstjerne', 'Answer 100 questions correctly across science, math, biology, anatomy, space and technology', 'Svar rigtigt på 100 spørgsmål på tværs af videnskab, matematik, biologi, anatomi, rummet og teknologi', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-384', 'STEM Superstar', 'Naturfagssuperstjerne', 'Answer 250 questions correctly across science, math, biology, anatomy, space and technology', 'Svar rigtigt på 250 spørgsmål på tværs af videnskab, matematik, biologi, anatomi, rummet og teknologi', 'Cross-Tag', 'platinum', 'epic', NULL),
('ACH-385', 'Body of Knowledge', 'Kend din krop', 'Answer 50 questions correctly across anatomy and biology', 'Svar rigtigt på 50 spørgsmål på tværs af anatomi og biologi', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-386', 'Rocket Scientist', 'Raketforsker', 'Answer 60 questions correctly across space and science', 'Svar rigtigt på 60 spørgsmål på tværs af rummet og videnskab', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-387', 'Humanities Hero', 'Humaniorahelt', 'Answer 150 questions correctly across history, mythology, religion, politics and royalty', 'Svar rigtigt på 150 spørgsmål på tværs af historie, mytologi, religion, politik og kongelige', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-388', 'Quiz Historian', 'Quizhistoriker', 'Answer 150 questions correctly across history, world-war-2, vikings and mythology', 'Svar rigtigt på 150 spørgsmål på tværs af historie, 2. verdenskrig, vikinger og mytologi', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-389', 'Word Nerd', 'Ordnørd', 'Answer 150 questions correctly across language, wordplay, riddles and books', 'Svar rigtigt på 150 spørgsmål på tværs af sprog, ordspil, gåder og bøger', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-390', 'Sports Desk', 'Sportsredaktionen', 'Answer 60 questions correctly across sports, football and olympics', 'Svar rigtigt på 60 spørgsmål på tværs af sport, fodbold og OL', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-391', 'Bon Vivant', 'Livsnyder', 'Answer 75 questions correctly across food-drink, cocktails and fashion', 'Svar rigtigt på 75 spørgsmål på tværs af mad og drikke, cocktails og mode', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-392', 'Eurovision Ready', 'Grand Prix-klar', 'Answer 50 questions correctly across music and danish-culture', 'Svar rigtigt på 50 spørgsmål på tværs af musik og dansk kultur', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-393', 'Local Legend', 'Lokal legende', 'Answer 100 questions correctly across danish-culture and vikings', 'Svar rigtigt på 100 spørgsmål på tværs af dansk kultur og vikinger', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-394', 'Copenhagen Nights', 'Københavnske nætter', 'Answer a danish-culture question correctly between 10 PM and 4 AM', 'Svar rigtigt på et spørgsmål om dansk kultur mellem kl. 22 og kl. 4', 'Cross-Tag', 'bronze', 'common', NULL),
('ACH-395', 'Jul in July', 'Jul i juli', 'Answer a christmas question correctly in July', 'Svar rigtigt på et julespørgsmål i juli', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-396', 'Foodie Friday', 'Fredagsbar', 'Answer a food-drink or cocktails question correctly on a Friday', 'Svar rigtigt på et spørgsmål om mad og drikke eller cocktails på en fredag', 'Cross-Tag', 'bronze', 'common', NULL),
('ACH-397', 'Sunday Funday', 'Søndagshygge', 'Answer a sports or games question correctly on a Sunday', 'Svar rigtigt på et spørgsmål om sport eller spil på en søndag', 'Cross-Tag', 'bronze', 'common', NULL),
('ACH-398', 'Binge Session', 'Seriemaraton', 'Answer 25 tv-shows questions correctly in one day', 'Svar rigtigt på 25 spørgsmål om tv-serier på én dag', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-399', 'Breaking News', 'Breaking news', 'Answer 10 current-events questions correctly in one day', 'Svar rigtigt på 10 spørgsmål om aktuelle emner på én dag', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-400', 'Morning Paper', 'Morgenavisen', 'Answer a current-events question correctly before 9 AM', 'Svar rigtigt på et spørgsmål om aktuelle emner før kl. 9', 'Cross-Tag', 'bronze', 'common', NULL),
('ACH-401', 'Zoo Day', 'Zoo-dag', 'Answer 15 animals questions correctly in one day', 'Svar rigtigt på 15 spørgsmål om dyr på én dag', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-402', 'Head Scratcher', 'Hovedbrud', 'Think for 20+ seconds on a riddle, then answer correctly', 'Tænk i mindst 20 sekunder over en gåde – og svar så rigtigt', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-403', 'Truth Streak', 'Sandhedsstime', 'Answer 15 true-false questions correctly in a row', 'Svar rigtigt på 15 sandt/falsk-spørgsmål i træk', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-405', 'Crossover Episode', 'Crossover-afsnit', 'In one game, answer correctly in 5 different tags', 'Svar rigtigt inden for 5 forskellige emner i ét spil', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-406', 'Genre Bender', 'Genrehopper', 'In one game, answer correctly in 8 different tags', 'Svar rigtigt inden for 8 forskellige emner i ét spil', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-407', 'Tag Curious', 'Emnenysgerrig', 'Answer at least one question in 10 different tags', 'Besvar mindst ét spørgsmål i 10 forskellige emner', 'Cross-Tag', 'bronze', 'common', NULL),
('ACH-408', 'Tag Tourist', 'Emneturist', 'Answer at least one question in 25 different tags', 'Besvar mindst ét spørgsmål i 25 forskellige emner', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-409', 'Tag Explorer', 'Emneopdager', 'Answer at least one question in every tag', 'Besvar mindst ét spørgsmål i hvert emne', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-410', 'Tag Completionist', 'Emnesamler', 'Answer at least one question correctly in every tag', 'Svar rigtigt på mindst ét spørgsmål i hvert emne', 'Cross-Tag', 'platinum', 'epic', NULL),
('ACH-411', 'Niche Hunter', 'Nichejæger', 'Answer correctly in every tag with fewer than 10 questions', 'Svar rigtigt i alle emner med færre end 10 spørgsmål', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-412', 'Deep Cuts', 'De skjulte perler', 'Answer 30 questions correctly across all tags with fewer than 20 questions', 'Svar rigtigt på 30 spørgsmål på tværs af alle emner med færre end 20 spørgsmål', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-413', 'Mainstream Master', 'Mainstream-mester', 'Reach the top ladder tier in the 5 largest tags (movies, danish-culture, current-events, tv-shows, music)', 'Nå øverste niveau i de 5 største emner (film, dansk kultur, aktuelle emner, tv-serier og musik)', 'Cross-Tag', 'legendary', 'legendary', NULL),
('ACH-414', 'Renaissance 2.0', 'Renæssance 2.0', 'Reach at least the second ladder tier in 15 different tags', 'Nå mindst andet niveau i 15 forskellige emner', 'Cross-Tag', 'platinum', 'epic', NULL),
('ACH-415', 'Polymath Supreme', 'Polyhistor', 'Answer 1,000 questions correctly across the 5 largest tags', 'Svar rigtigt på 1.000 spørgsmål på tværs af de 5 største emner', 'Cross-Tag', 'diamond', 'legendary', NULL),
('ACH-416', 'Well Rounded', 'Bredt funderet', 'Have at least 10 correct answers in 20 different tags', 'Hav mindst 10 rigtige svar i 20 forskellige emner', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-417', 'One-Track Mind', 'Fagidiot', 'Answer 500 questions correctly in a single tag', 'Svar rigtigt på 500 spørgsmål i ét enkelt emne', 'Cross-Tag', 'gold', 'rare', NULL),
('ACH-418', 'Theme Night', 'Temaaften', 'Finish a Party game where every question came from a single tag', 'Gennemfør et Party Mode-spil, hvor alle spørgsmål kom fra ét emne', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-419', 'Danish Party', 'Dansk aften', 'Host a Party game featuring danish-culture questions with 4+ players', 'Vær vært for et Party Mode-spil med spørgsmål om dansk kultur og mindst 4 spillere', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-420', 'Movie Night Host', 'Vært for filmaften', 'Host a Party game featuring movies questions with 4+ players', 'Vær vært for et Party Mode-spil med filmspørgsmål og mindst 4 spillere', 'Cross-Tag', 'silver', 'uncommon', NULL),
('ACH-421', 'Quiz Curator', 'Quizkurator', 'Play games featuring the 10 largest tags at least once each', 'Spil mindst ét spil med hvert af de 10 største emner', 'Cross-Tag', 'silver', 'uncommon', NULL);
