-- Reword questions that referenced a floating "this year"/"recently"/"just
-- now" point in time (following the same pattern as the earlier
-- "currently in cinemas" cinema-question fix). Each statement either
-- drops the relative-time phrase (when the rest of the question already
-- has enough durable, dateable detail to stand on its own) or anchors it
-- to a specific year inferred from the quiz's own content/filename.
UPDATE "Question" SET "prompt" = 'Denne komiker har lavet showet ''Enestående'', har tidligere lavet forestillinger til børn og har været vært på ''Husk lige Tandbørsten Version 2''. Hvem er han?' WHERE "prompt" = 'Denne dejlige komiker er i øjeblikket aktuel med showet ''Enestående''. Han har tidligere lavet forestillinger til børn og har været vært på ''Husk lige Tandbørsten Version 2''. Hvem er han?';
UPDATE "Question" SET "prompt" = 'Går man ind ad indgangen til Zoologisk Have i Odense og den forkerte vej, er det første dyr man ser et dyr, der normalt bor alene. Det sover det meste af dagen, har en smuk rød farve og er noget af det kæreste. Hvilket dyr er det?' WHERE "prompt" = 'Går man ind ad indgangen til Zoologisk Have i Odense og den forkerte vej, er det første dyr man ser, et dyr der normalt bor alene, men for nylig har fået en ny ven. Det sover det meste af dagen, har en smuk rød farve og er noget af det kæreste. Hvilket dyr er det?';
UPDATE "Question" SET "prompt" = 'Hvilken film fortæller den ufortalte oprindelseshistorie om, hvordan Vlad Palisador blev til Dracula for at redde sit rige fra det osmanniske rige?' WHERE "prompt" = 'Snart kan vi i biografen få den ufortalte historie om en af vor tids største monster-ikoner.';
UPDATE "Question" SET "prompt" = 'Denne nulevende, dømte morder er både gift og har fået et barn, men var ikke den største fan af sin mor. Hvem er han?' WHERE "prompt" = 'Denne nulevende, dømte morder er både gift og har for nylig fået et barn, men var ikke den største fan af sin mor. Hvem er han?';
UPDATE "Question" SET "prompt" = 'Ved Miss Universe-finalen i 2015 gik alt godt, lige indtil kronen skulle overrækkes. Hvad skete der?' WHERE "prompt" = 'Ved Miss Universe-finalen for nyligt gik alt godt, lige indtil kronen skulle overrækkes. Hvad skete der?';
UPDATE "Question" SET "prompt" = 'I Tyskland blev en mand sagsøgt for ca. 14.000 kroner, da han havde svært ved at ramme toilettet og derved lavede urinskader på marmorgulvet. Hvad skete der i retten?' WHERE "prompt" = 'I Tyskland blev en mand for nyligt sagsøgt for ca. 14.000 kroner, da han havde svært ved at ramme toilettet og derved lavede urinskader på marmorgulvet. Hvad skete der i retten?';
UPDATE "Question" SET "prompt" = 'Den næste reality-babe er lidt af et firben og har afsløret, at hun er gravid. Hvad er hendes kaldenavn?' WHERE "prompt" = 'Den næste reality-babe er lidt af et firben og har for nyligt afsløret, at hun er gravid. Hvad er hendes kaldenavn?';
UPDATE "Question" SET "prompt" = 'En mand svømmede en tur i en sø, men da han kom op, var hans ene øre stoppet af noget. Hvad var det?' WHERE "prompt" = 'En mand svømmede for nylig en tur i en sø, men da han kom op, var hans ene øre stoppet af noget. Hvad var det?';
UPDATE "Question" SET "prompt" = 'En rød-ryggede edderkop og en østlig brunslange stødte på hinanden i Australien, da slangen sad fast i et edderkoppespind. Hvem vandt den farlige kamp?' WHERE "prompt" = 'En rød-ryggede edderkop og en østlig brunslange stødte for nyligt på hinanden i Australien, da slangen sad fast i et edderkoppespind. Hvem vandt den farlige kamp?';
UPDATE "Question" SET "prompt" = 'Det gik galt for en kioskejer i Norge. Hvad skete der?' WHERE "prompt" = 'Det gik galt for en kioskejer i Norge for nylig. Hvad skete der?';
UPDATE "Question" SET "prompt" = 'Sagde Dronningen dette i sin nytårstale ved indgangen til 2015: ”Al begyndelse er svær, men glæden er stor, når det lykkes.”?' WHERE "prompt" = 'Sagde Dronningen dette i sin nytårstale i år: ”Al begyndelse er svær, men glæden er stor, når det lykkes.”?';
UPDATE "Question" SET "prompt" = 'Sagde Dronningen dette i sin nytårstale ved indgangen til 2015: ”Overalt i landet gøres der en stor indsats for at hjælpe flygtningene.”?' WHERE "prompt" = 'Sagde Dronningen dette i sin nytårstale i år: ”Overalt i landet gøres der en stor indsats for at hjælpe flygtningene.”?';
UPDATE "Question" SET "prompt" = 'Sagde Dronningen dette i sin nytårstale ved indgangen til 2015: ”Vi har alle i år mindedes Stormen på Dybbøl, og de fleste har set serien. Dette foregik i år den 18. april.”?' WHERE "prompt" = 'Sagde Dronningen dette i sin nytårstale i år: ”Vi har alle i år mindedes Stormen på Dybbøl, og de fleste har set serien. Dette foregik i år den 18. april.”?';
UPDATE "Question" SET "prompt" = 'Sandt eller falsk: I Kastrup fangede man i 2014 en kvinde med en stjålet halskæde til en værdi af 130 kr. i maven.' WHERE "prompt" = 'Sandt eller falsk: I Kastrup fangede man sidste år en kvinde med en stjålet halskæde til en værdi af 130 kr. i maven.';
UPDATE "Question" SET "prompt" = 'Hvor mange dumpede i 2014 deres køreprøve på Fyn?' WHERE "prompt" = 'Hvor mange dumpede sidste år deres køreprøve på Fyn?';
UPDATE "Question" SET "prompt" = 'Red Devils er en faldskærmsgruppe, som opfører avanceret luftakrobatik. En dag gik det galt, da den ene af to faldskærmsudspringere i en duo ikke fik sin skærm til at folde ud. Hvad skete der?' WHERE "prompt" = 'Red Devils er en faldskærmsgruppe, som opfører avanceret luftakrobatik. For nylig gik det galt, da den ene af to faldskærmsudspringere i en duo ikke fik sin skærm til at folde ud. Hvad skete der?';
UPDATE "Question" SET "prompt" = 'Kim Kardashian har udgivet en bog, som ikke har fået særlig gode anmeldelser. Hvad handlede bogen om?' WHERE "prompt" = 'Kim Kardashian har for nylig udgivet en bog, som ikke har fået særlig gode anmeldelser. Hvad handlede bogen om?';
UPDATE "Question" SET "prompt" = 'Japanerne hævede barren for mærkelige gameshows: to unge japanske kvinder puster om kap i et plastikrør, hvori der befinder sig hvad?' WHERE "prompt" = 'Japanerne hævede for nyligt barren for mærkelige gameshows: to unge japanske kvinder puster om kap i et plastikrør, hvori der befinder sig hvad?';
UPDATE "Question" SET "prompt" = 'En kendt rapper har begæret konkurs, efter at hans firmaer er kørt dårligt, og der er kommet en kæmpe erstatning for en lækket sexvideo. Hans kunstnernavn antyder, at han ikke har meget tilbage. Hvem er han?' WHERE "prompt" = 'En kendt rapper har for nyligt begæret konkurs, efter at hans firmaer er kørt dårligt, og der er kommet en kæmpe erstatning for en lækket sexvideo. Hans kunstnernavn antyder, at han ikke har meget tilbage. Hvem er han?';
UPDATE "Question" SET "prompt" = 'Rumsonden New Horizons kunne for første gang vise højkvalitetsbilleder af denne kendte himmellegeme, som ikke kan bestemme sig for, om det skal være en planet eller ej. Hvad er der taget billeder af?' WHERE "prompt" = 'Rumsonden New Horizons kunne for nyligt for første gang vise højkvalitetsbilleder af denne kendte himmellegeme, som ikke kan bestemme sig for, om det skal være en planet eller ej. Hvad er der taget billeder af?';
UPDATE "Question" SET "prompt" = 'Hvilken hård konkurrence gennemførte kronprinsen?' WHERE "prompt" = 'Hvilken hård konkurrence gennemførte kronprinsen for nylig?';
UPDATE "Question" SET "prompt" = 'Hvilken vinglad franskmand rundede et flot hjørne, da han blev 80 år?' WHERE "prompt" = 'Hvilken vinglad franskmand rundede for nyligt et flot hjørne, da han blev 80 år?';
